language: go

sudo: false

go: master

before_install:
  - go get github.com/WindomZ/go-develop-kit/path
  - go get github.com/WindomZ/leetcode-graphql
  - go get github.com/lunny/html2md
  - go get github.com/WindomZ/testify/assert
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint ./...)
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -service=travis-ci
  - go test -v ./leetcode
